export interface Expense {
  id: string;
  date: string; // ISO date, YYYY-MM-DD
  merchant: string;
  amount: number;
  categoryId: string;
  accountId: string;
  notes?: string;
  recurringId?: string; // set if this expense was generated by a RecurringExpense template
}

export interface RecurringExpense {
  id: string;
  merchant: string;
  amount: number;
  categoryId: string;
  accountId: string;
  notes?: string;
  frequency: 'monthly';
  startDate: string; // ISO date of the first occurrence
  occurrences?: number; // undefined = ongoing indefinitely; number = ends after N payments
  active: boolean; // false once cancelled or all occurrences have been generated
}

export interface Category {
  id: string;
  name: string;
  color: string;
}

export interface Account {
  id: string;
  name: string;
  type: string;
  balance: number; // manually set by the user; the app never recalculates this from expenses
}

export interface SubtrackSync {
  targetAccountId: string | null; // which account receives synced SubTrack payments
  syncedPaymentIds: string[]; // SubTrack payment ids already applied, so re-syncing is idempotent
}

export interface AppData {
  expenses: Expense[];
  categories: Category[];
  accounts: Account[];
  recurringExpenses: RecurringExpense[];
  subtrackSync: SubtrackSync;
}

export type SortField = 'date' | 'amount' | 'merchant' | 'category';
export type SortOrder = 'asc' | 'desc';
export type Tab = 'dashboard' | 'expenses' | 'add' | 'categories' | 'accounts' | 'settings';
